// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package no.jpro.rootest.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Aktivitet_Roo_Configurable {
    
    declare @type: Aktivitet: @Configurable;
    
}
