// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package no.jpro.rootest.domain;

import java.util.Calendar;

privileged aspect Timelisterad_Roo_JavaBean {
    
    public Calendar Timelisterad.getDato() {
        return this.dato;
    }
    
    public void Timelisterad.setDato(Calendar dato) {
        this.dato = dato;
    }
    
}
